apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord-alert
  labels:
    release: prometheus
spec:
  route:
    receiver: discord
    matchers: # 配對條件
      - name: severity
        value: warning
      - name: alertname
        matchType: "=~"
        value: "Nginx.*" # 只匹配 Nginx 開頭的告警`125`
  receivers:
    - name: discord
      webhookConfigs:
        - url: "http://alertmanager-discord.default.svc:9094"
          sendResolved: true
