version: "3"

services:
  keycloak:
    container_name: keycloak
    image: docker.io/bitnami/keycloak:21.1.2
    depends_on:
      - postgresql-kc
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgresql-kc
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=bitnami_keycloak
      - KEYCLOAK_DATABASE_USER=bn_keycloak
    ports:
      - "80:8080"

  postgresql-kc:
    container_name: postgresql-kc
    image: docker.io/bitnami/postgresql:15
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - "postgresql_data:/bitnami/postgresql"

  grafana:
    container_name: grafana
    image: grafana/grafana:11.5.2
    ports:
      - "3000:3000"
    environment:
      # Grafana 基本設定
      - GF_SERVER_ROOT_URL=http://localhost:3000
      # OIDC 設定（指向 Keycloak）
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Keycloak
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=<YOUR_CLIENT_SECRET>
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=http://localhost/realms/master/protocol/openid-connect/auth
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=http://keycloak:8080/realms/master/protocol/openid-connect/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=http://keycloak:8080/realms/master/protocol/openid-connect/userinfo
      - GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH=contains(realm_access.roles[*], 'admin') && 'Admin' || 'Viewer'
    volumes:
      - "grafana_data:/var/lib/grafana"
    depends_on:
      - keycloak

volumes:
  postgresql_data:
    driver: local
  grafana_data:
    driver: local
